---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/username/public_html/development/testOne/
    - /bin/rm -rf $DEPLOY_PATH/*                  # Clear old files
    - /bin/cp -Rf . $DEPLOY_PATH                  # Copy everything
    - /bin/chmod -R 755 $DEPLOY_PATH              # Fix permissions
    - /usr/local/bin/npm install --production     # Install Node.js deps
    - /usr/local/bin/npm run build                # Build React/Vue